role: miner

chain:
  netuid: 2
  endpoint: ws://0.0.0.0:9945

wallet:
  name: local-miner
  hotkey: default

subtensor:
  network: local

axon:
  host: 0.0.0.0
  port: 8094

miner:
  allow_connection_info_from_unpermitted_validators: true

database:
  host: 127.0.0.1
  port: 5435
  user: sparket
  name: sparket

